### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by Kanha-Guleria** [Mohit-Guleria/Shopify#4]
Hi Team,

In custom page header and footer are missing from the custom cart page.

Thanks

**Comment by MohitGuleria-CS** [comment]
Hi @Kanha-Guleria,

I have resolved the issue with the custom cart page missing the header and footer. Please review the screenshot and let me know if there is anything else you need.

**Screenshot: ** https://tinyurl.com/2ygsdkf7

Thanks

**Comment by MohitGuleria-CS** [comment]
I have resolved the issue with the custom cart page missing the header and footer. Please review the screenshot and let me know if there is anything else you need.

**Screenshot:** https://tinyurl.com/2ygsdkf7

Thanks

**Comment by Kanha-Guleria** [comment]
Thank You! @MohitGuleria-CS 

Let me check and get back to you shortly.

**Comment by Kanha-Guleria** [comment]
Looks Fine Now. 

Please move the changes on the main Branch.

**Comment by MohitGuleria-CS** [comment]
@Kanha-Guleria Changes moved to the main branch. 

Thanks
