### ISSUE TITLE
Empty Cart Page

### ISSUE THREAD

**Issue by Kanha-Guleria** [Mohit-Guleria/Shopify#5]
Hi Team,

When the page is empty and Shop page link is missing from the page also I don't know why the proceed to checkout page there is there is no product added on the custom cart page.

**Screenshot :** https://prnt.sc/BRu3aivLcGzn

Thanks

**Comment by MohitGuleria-CS** [comment]
@Kanha-Guleria,

I have fixed the issue you shared with me on the empty cart page.

**Preview URL:** https://n1kao8gnh40ahp7i-65659011255.shopifypreview.com/cart?view=custom-cart
**Screenshot:** https://tinyurl.com/2xoatugn

Thanks

**Comment by Kanha-Guleria** [comment]
@MohitGuleria-CS  Looks fine. 

Move to main Branch

Thank You!

**Comment by MohitGuleria-CS** [comment]
@Kanha-Guleria I already did that. 

Thanks
